language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: bionic
          sudo: required
          python: 3.6

        - os: linux
          dist: bionic
          sudo: required
          python: 3.7

        - os: linux
          dist: bionic
          sudo: required
          python: 3.8

install:
    - pip install --upgrade pip setuptools wheel
    - pip install coveralls codecov pyflakes
    - pip install -r requirements.txt
    - python3 -m coverage run -a setup.py install
    - pip install git+https://github.com/dvolgyes/zenodo_get

script:
  - tests/test.sh

after_success:
  - coveralls
  - codecov
